#!/usr/bin/env bash
name="glibmm"
version="2.66.6"
url="https://www.gtkmm.org"
description="C++ bindings for GLib"
source="https://download.gnome.org/sources/glibmm/${version%.*}/glibmm-${version}.tar.xz"
depends="glib,libsigc++2"
group="dev.cpp"
export PATH=$HOME:$PATH

setup () {
ln -s /bin/true $HOME/dot
cd $SOURCEDIR
    meson setup $BUILDDIR --prefix=/usr \
        --libdir=/usr/lib64/
}

build () {
    ninja -C $BUILDDIR $jobs
}

package () {
    DESTDIR=${DESTDIR} ninja -C $BUILDDIR install $jobs
}


