#!/usr/bin/env bash
name="granite"
version="6.2.0"
description="Library that extends GTK with common widgets and utilities"
source="https://github.com/elementary/granite/archive/refs/tags/$version.tar.gz"
depends="gtk3,libgee"
builddepend="glib,gobject-introspection,gtk3,libgee,meson,sassc,vala"
group="dev.libs"


setup () {
	cd $SOURCEDIR
    meson setup $BUILDDIR --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    meson compile -C $BUILDDIR
}

package(){
    DESTDIR="$DESTDIR" meson install -C $BUILDDIR
}

