#!/usr/bin/env bash
name="libatasmart"
version="0.19-5"
description="A small and lightweight parser library for ATA S.M.A.R.T. hard disks"
source="https://salsa.debian.org/utopia-team/libatasmart/-/archive/debian/$version/libatasmart-debian-$version.tar.gz"
depends=""
builddepend=""
group="dev.libs"

setup(){
	cd $SOURCEDIR
   	./autogen.sh
	./configure --prefix=/usr \
        --libdir=/usr/lib64/ 
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

