#!/usr/bin/env bash
name="libsodium"
version="1.0.19"
description="P(ortable|ackageable) NaCl-based crypto library"
source="https://github.com/jedisct1/libsodium/releases/download/${version}-RELEASE/libsodium-${version}.tar.gz"
depends=""
builddepend=""
group="dev.libs"

setup(){
    cd $SOURCEDIR
    ./configure  --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

