#!/usr/bin/env bash
name="pipewire"
version="1.0.0"
url="https://pipewire.org/"
description="Multimedia processing graphs "
source="https://gitlab.freedesktop.org/pipewire/pipewire/-/archive/$version/pipewire-$version.tar.gz"
depends="lilv,libpulse,alsa-lib,dbus"
group="media.video"
uses="alsa gstreamer bluetooth jack"

setup(){
cd $SOURCEDIR
        cp $PACKAGEDIR/pipewire.desktop ./
        cp $PACKAGEDIR/pipewire-launcher.sh ./
   meson setup $BUILDDIR --prefix=/usr \
    --libdir=/usr/lib64 \
    -D gstreamer=disabled\
    -D gstreamer-device-provider=disabled \
    -D pipewire-alsa=disabled\
    -D alsa=disabled\
    -D jack=disabled\
    -D bluez5=disabled\
    -D bluez5-backend-hsp-native=disabled\
    -D bluez5-backend-hfp-native=disabled\
    -D bluez5-codec-opus=disabled\
    -D v4l2=disabled\
    -D session-managers=[]
}
build(){
   ninja -C $BUILDDIR
}

package(){
    DESTDIR=$DESTDIR ninja -C $BUILDDIR install
    mkdir -p ${DESTDIR}/usr/libexec ${DESTDIR}/etc/xdg/autostart/
    # pipewire launcher from alpine linux
    install pipewire-launcher.sh ${DESTDIR}/usr/libexec/pipewire-launcher
    install pipewire.desktop ${DESTDIR}/etc/xdg/autostart/
    
}
