#!/usr/bin/env bash
name="gst-plugins-good"
version="1.18.6"
description="GStreamer plugins"
source="https://gitlab.freedesktop.org/gstreamer/gst-plugins-good/-/archive/${version}/gst-plugins-good-${version}.tar.gz"
depends="gstreamer,gst-plugins-base"
group="media.video"


setup(){
	cd $SOURCEDIR
	 meson setup $BUILDDIR --prefix=/usr \
    --libdir=/usr/lib64
}
build(){
   ninja -C $BUILDDIR
}

package(){
    DESTDIR=$DESTDIR ninja -C $BUILDDIR install
}
