#!/usr/bin/env bash
name="libgee"
version="0.20.6"
description="A collection library providing GObject-based interfaces and classes for commonly used data structures"
source="https://download.gnome.org/sources/libgee/${version%.*}/libgee-${version}.tar.xz"
depends="glib"
builddepend="gobject-introspection,vala"
group="dev.libs"


setup () {
	cd $SOURCEDIR
    ./configure --prefix=/usr \
		--libdir=/usr/lib64/ \
		--build=$CBUILD \
		--host=$CHOST
}

build () {
    make
}

package () {
    make DESTDIR="$DESTDIR" install
}

