#!/usr/bin/env bash
name="lightdm-pardus-greeter"
version="master"
url="https://github.com/pardus/pardus-lightdm-greeter"
description="Lightdm greeter for Pardus"
source=('https://github.com/pardus/pardus-lightdm-greeter/archive/refs/heads/master.zip')
depends="lightdm,py3-pygobject,py3-cairo"
group="x11.misc"
setup()
{
cd $SOURCEDIR
}
build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
    sed -i 's/TÜBİTAK ULAKBİM/BASİT DAĞITIM/g' $DESTDIR/usr/share/pardus/pardus-lightdm-greeter/data/main.ui
}

