#!/usr/bin/env bash
name="ndctl"
version="77"
description="Helper tools and libraries for managing non-volatile memory on Linux"
source="https://github.com/pmem/ndctl/archive/refs/tags/v$version.tar.gz"
depends="json-c,kmod,libtraceevent,libtracefs,keyutils,iniparser"
builddepend=""
group="sys.block"

setup(){
	cd $SOURCEDIR
	meson setup $BUILDDIR --prefix=/usr \
            --libdir=/usr/lib64/ \
            -Ddocs=disabled \
            -Dsystemd=disabled \
            -Dtest=disabled
}

build(){
    ninja -C $BUILDDIR
}

package(){
   DESTDIR=$DESTDIR ninja -C $BUILDDIR install
}

