#!/usr/bin/env bash
name="gedit"
version="47.0"
description="gedit is the GNOME text editor"
source="https://download.gnome.org/sources/gedit/${version%.*}/gedit-${version}.tar.xz"
depends="cairo,dconf,gdk-pixbuf2,gsettings-desktop-schemas,pango,libgedit-tepl"
builddepend="glib,gobject-introspection,gspell,gtk3,gtk-doc,itstool,libgedit-gtksourceview,libpeas,libx11,libxml2,meson,perl"
group="app.editors"


setup(){
    cd $SOURCEDIR
    meson setup $BUILDDIR \
        --prefix=/usr \
        --libdir=/usr/lib64

}
build(){
    meson compile -C $BUILDDIR
}

package(){
    DESTDIR="$DESTDIR" meson install -C $BUILDDIR
}

