#!/usr/bin/env bash
name="volume_key"
version="0.3.12"
description="A library for manipulating storage volume encryption keys and storing them separately from volumes to handleforgotten passphrases, and the associated command-line tool "
source="https://pagure.io/volume_key/archive/volume_key-$version/volume_key-volume_key-$version.tar.gz"
depends="cryptsetup,nss,nspr,swig,gpgme"
group="dev.libs"


setup(){
	cd $SOURCEDIR
	
	autoreconf -fvi
	export CFLAGS+=" $(python3-config --includes)"
	./configure --prefix=/usr \
		--libdir=/usr/lib64/ \
		--sysconfdir=/etc \
		--localstatedir=/var \
		--with-python3
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

