#!/usr/bin/env bash
name="libndp"
version="1.8"
description="libndp Library for Neighbor Discovery Protocol"
source="https://github.com/jpirko/libndp/archive/refs/tags/v$version.tar.gz"
depends=""
builddepend=""
group="net.libs"


setup(){
	cd $SOURCEDIR
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

