#!/usr/bin/env bash
name="waf"
version="2.1.1"
description="General-purpose build system modelled after Scons"
source="https://gitlab.com/ita1024/waf/-/archive/waf-$version/waf-waf-$version.tar.gz"
depends="python"
builddepend=""
group="media.libs"

setup(){
    cd $SOURCEDIR
    echo ""
}
build(){
    python3 ./waf-light configure build
}

package(){
    make install DESTDIR=$DESTDIR
    install -vDm 755 waf -t "$DESTDIR/usr/bin"
	install -vDm 644 wscript -t "$DESTDIR/usr/share/$name/"

	install -vDm 644 waflib/*.py -t "$DESTDIR/usr/lib64/python3/site-packages/waf/waflib/"
	install -vDm 644 waflib/Tools/*.py -t "$DESTDIR/usr/lib64/python3/site-packages/waf/waflib/Tools/"
	install -vDm 644 waflib/extras/*.py -t "$DESTDIR/usr/lib64/python3site-packages/waf/waflib/extras/"
	python3 -m compileall -d "/usr/lib64/python3" "$DESTDIR/usr/lib64/python3"
	python3 -O -m compileall -d "/usr/lib64/python3" "$DESTDIR/usr/lib64/python3/"
	#install -vDm 644 LICENSE -t "$pkgdir/usr/share/licenses/$name/"
	#  install -vDm 644 {README,../building-waf}.md -t "$pkgdir/usr/share/doc/$name/"

}
