#!/usr/bin/env bash
name="autofs"
version="5.1.8"
description="A kernel-based automounter for Linux"
#source=("https://mirrors.edge.kernel.org/pub/linux/daemons/autofs/v5/autofs-${version}.tar.gz")
source="https://www.kernel.org/pub/linux/daemons/${name}/v5/${name}-${version}.tar.xz"
depends=""
builddepend=""
group="net.fs"


setup(){
	cp -prvf $PACKAGEDIR/files/ /tmp/bps/build/
	cd $SOURCEDIR
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
		--sysconfdir=/etc/autofs \
		--with-mapdir=/etc/autofs \
		--with-confdir=/etc/conf.d \
		--without-hesiod \
		--with-libtirpc \
		--enable-sloppy-mount \
		--enable-force-shutdown \
		--enable-ignore-busy
}

build(){
    make
}

package(){
    make DESTDIR="$DESTDIR" install

	mkdir -p "$DESTDIR"/etc/autofs/
	install -m644 samples/auto.master \
		samples/auto.misc \
		samples/auto.net \
		samples/auto.smb \
		"$DESTDIR"/etc/autofs/

	install -m755 -D ../files/$name.initd \
		"$DESTDIR"/etc/init.d/$name

	install -m644 -D ../files/$name.confd \
		"$DESTDIR"/etc/conf.d/$name
}

