#!/usr/bin/env bash
name="pangomm"
version="2.46.3"
url="https://www.gtkmm.org/"
description="C++ bindings for Pango"

source="https://download.gnome.org/sources/pangomm/${version%.*}/pangomm-${version}.tar.xz"
depends=""
group="dev.cpp"

setup () {
cd $SOURCEDIR
    meson setup $BUILDDIR --prefix=/usr \
		--libdir=/usr/lib64/
}

build () {
    ninja -C $BUILDDIR $jobs
}

package () {
    DESTDIR=${DESTDIR} ninja -C $BUILDDIR install $jobs
}

