#!/usr/bin/env bash
name="libogg"
version="1.3.5"
url="https://xiph.org/ogg/"
description="The Ogg media file format library"
source="https://downloads.xiph.org/releases/ogg/libogg-$version.tar.gz"
depends=""
group="media.libs"

setup(){
cd $SOURCEDIR
  autoreconf -fiv
   ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install DESTDIR=$DESTDIR $jobs
}

