#!/usr/bin/env bash
name="gnome-desktop"
version="44.0"
description="GNOME desktop core libraries"
source="https://download.gnome.org/sources/gnome-desktop/${version%.*}/gnome-desktop-$version.tar.xz"
depends=""
builddepend=""
group="gnome.base"


setup(){
    cd $SOURCEDIR
    meson setup $BUILDDIR \
    	--prefix=/usr \
        --libdir=/usr/lib64/ \
		-Dudev=enabled \
        -Db_lto=true \
		-Dbuild_gtk4=false \
		-Dlegacy_library=true
}
build(){
    meson compile -C $BUILDDIR
}

package(){
    DESTDIR="$DESTDIR" meson install -C $BUILDDIR
}
