#!/usr/bin/env bash
name="libnvme"
version="1.7.1"
description="C Library for NVM Express on Linux"
source="https://github.com/linux-nvme/libnvme/archive/refs/tags/v${version}/libnvme-${version}.tar.gz"
depends="json-c,openssl,linux-headers"
builddepend=""
group="sys.libs"


setup () {
	cd $SOURCEDIR
    meson setup $BUILDDIR --prefix=/usr \
		--libdir=/usr/lib64/ \
		-Db_lto=true \
		-Ddefault_library=both
}

build () {
    ninja -C $BUILDDIR
}

package () {
    DESTDIR="$DESTDIR" ninja -C $BUILDDIR install
}

