#!/usr/bin/env bash
name="libsigc++2"
version='2.12.0'
url="https://example.org"
description="Typesafe callback system for standard C++"
source="https://download.gnome.org/sources/libsigc++/${version%.*}/libsigc++-$version.tar.xz"
group="dev.libs"

setup () {
cd $SOURCEDIR
    meson setup $BUILDDIR --prefix=/usr \
     --libdir=/usr/lib64/
}

build () {
    ninja -C $BUILDDIR  $jobs
}

package () {
   DESTDIR=$DESTDIR ninja -C $BUILDDIR  install $jobs
}

