#!/usr/bin/env bash
name="gstreamer"
version="1.24.5"
description="Multimedia graph framework - core"
source="https://gitlab.freedesktop.org/gstreamer/gstreamer/-/archive/${version}/gstreamer-${version}.tar.bz2"
depends="glib,elfutils,libxml2"
builddepend=""
group="media.libs"

setup(){
	cd $SOURCEDIR
    meson setup $BUILDDIR \
    	--prefix=/usr \
        --libdir=/usr/lib64/ \
        -Dgood=disabled \
        -Dbad=disabled \
        -Dugly=disabled \
        -Dlibav=disabled \
		-Dintrospection=enabled
}

build(){
    meson compile -C $BUILDDIR
}

package(){
    DESTDIR="$DESTDIR" meson install -C $BUILDDIR
}
