#!/usr/bin/env bash
name="gst-plugins-bad"
version="1.18.6"
description=" GStreamer plugins and helper libraries"
source="https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/archive/${version}/gst-plugins-bad-${version}.tar.gz"
depends="gst-plugins-base"
buildepend=""
group="media.video"


# Fix undefined symbol "exp"
setup(){
	export CFLAGS="$CfLAGS -lm"
	cd $SOURCEDIR
	 meson setup $BUILDDIR --prefix=/usr \
    	--libdir=/usr/lib64
}
build(){
   ninja -C $BUILDDIR
}

package(){
    DESTDIR=$DESTDIR ninja -C $BUILDDIR install
}
