#!/usr/bin/env bash
name="networkmanager"
version="1.44.2"
description="network management daemon"
source="https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/archive/$version/NetworkManager-$version.tar.gz"
depends="libndp,nss,newt,iptables"
builddepend="libxslt,gobject-introspection,ppp"
group="net.misc.power"


setup(){
unset CFLAGS
unset CXXFLAGS

	cp -prvf $PACKAGEDIR/files/ /tmp/bps/build/
	cd $SOURCEDIR
    meson setup $BUILDDIR --prefix=/usr \
        --libdir=/usr/lib64/ \
        --libexecdir=/usr/lib64/ \
        -Dsession_tracking=no \
        -Dsession_tracking_consolekit=false \
        -Dselinux=false \
        -Dpolkit=false \
        -Dcrypto=nss \
        -Dsystemd_journal=false \
        -Dsystemdsystemunitdir=no \
        -Dqt=false \
        -Dselinux=false \
        -Dmodem_manager=false \
        -Dppp=true \
        -Dovs=true \
        -Dvapi=true \
        -Dtests=no

}

build(){
    ninja -C $BUILDDIR
}

package(){
    mkdir -p $DESTDIR/etc/init.d/
    mkdir -p $DESTDIR/etc/NetworkManager
    
    DESTDIR=$DESTDIR ninja -C $BUILDDIR install
    
    install -D -m644 ../files/networkmanager.initd "${DESTDIR}"/etc/init.d/networkmanager
    install -D -m644 ../files/networkmanager.conf "${DESTDIR}"/etc/NetworkManager/NetworkManager.conf
    install -D -m644 ../files/30-random-mac.conf "${DESTDIR}"/etc/NetworkManager/conf.d/
    install -D -m644 ../files/20-wifi-powersave.conf "${DESTDIR}"/etc/NetworkManager/conf.d/
    
	mkdir -p $DESTDIR/usr/lib64/
	mv $DESTDIR/usr/lib/* $DESTDIR/usr/lib64/
	rm -rf $DESTDIR/usr/lib

}

