#!/usr/bin/env bash
name="networkmanager"
version="1.46.0"
description="network management daemon"
source="https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/archive/$version/NetworkManager-$version.tar.gz"
depends="libndp,nss,newt,iptables"
builddepend="libxslt,gobject-introspection,ppp"
group="net.misc.power"


setup(){
unset CFLAGS
unset CXXFLAGS

	cp -prvf $PACKAGEDIR/files/ /tmp/bps/build/
	cd $SOURCEDIR
    meson setup $BUILDDIR --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Db_lto=true \
        -Dsession_tracking=no \
        -Dsession_tracking_consolekit=false \
        -Dsuspend_resume=elogind \
        -Dselinux=false \
        -Dpolkit=true \
        -Dcrypto=nss \
        -Dsystemd_journal=false \
        -Dsystemdsystemunitdir=no \
        -Dqt=false \
        -Dselinux=false \
        -Dmodem_manager=false \
        -Dppp=false \
        -Dovs=false \
        -Dvapi=false \
		-Dconfig_plugins_default=ifupdown \
		-Ddbus_conf_dir=/usr/share/dbus-1/system.d \
		-Ddhcpcd=false \
		-Difupdown=true \
		-Diptables=/sbin/iptables \
		-Diwd=true \
		-Dlibaudit=no \
		-Dmodify_system=true \
		-Dofono=true \
		-Dpppd=/usr/sbin/pppd \
		-Dpppd_plugin_dir=/usr/lib64/pppd/2.5.0 \
		-Dudev_dir=/lib64/udev \
        -Dtests=no

}

build(){
    #ninja -C $BUILDDIR
    meson compile -C $BUILDDIR
}

package(){
    mkdir -p $DESTDIR/etc/init.d/
    mkdir -p $DESTDIR/etc/NetworkManager
    
    #DESTDIR=$DESTDIR ninja -C $BUILDDIR install
    DESTDIR="$DESTDIR" meson install -C $BUILDDIR
    
    install -D -m644 ../files/networkmanager.initd "${DESTDIR}"/etc/init.d/networkmanager
    install -D -m644 ../files/networkmanager.conf "${DESTDIR}"/etc/NetworkManager/NetworkManager.conf
    install -D -m644 ../files/30-random-mac.conf "${DESTDIR}"/etc/NetworkManager/conf.d/
    install -D -m644 ../files/20-wifi-powersave.conf "${DESTDIR}"/etc/NetworkManager/conf.d/

}

