#!/usr/bin/env bash
name="libsoxr"
version="0.1.3"
description="The SoX Resampler library that aims to give fast and high quality results for any constant resampling ratio"
source="https://downloads.sourceforge.net/project/soxr/soxr-${version}-Source.tar.xz"
depends=""
builddepend="cmake, ninja"
group="media.libs"

setup(){
	cd $SOURCEDIR
    cmake -B $BUILDDIR -G Ninja \
		-DCMAKE_BUILD_TYPE=None \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DBUILD_EXAMPLES=OFF \
        -DBUILD_SHARED_LIBS=ON \
        -DWITH_AVFFT=ON \
        -DWITH_LSR_BINDINGS=ON \
        -DWITH_OPENMP=ON \
        -DWITH_PFFFT=ON

}

build(){
    cmake --build $BUILDDIR
}

package(){
   DESTDIR=$DESTDIR cmake --install $BUILDDIR
   mkdir -p $DESTDIR/usr/lib64
	mv $DESTDIR/usr/lib/* $DESTDIR/usr/lib64/
	rm -rf $DESTDIR/usr/lib
}

