#!/usr/bin/env bash
name="gst-plugins-base"
version="1.18.6"
description="GStreamer plugins and helper libraries"
source="https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/-/archive/${version}/gst-plugins-base-${version}.tar.gz"
depends="gstreamer"
group="media.video"


setup(){
	cd $SOURCEDIR
	 meson setup $BUILDDIR --prefix=/usr \
    	--libdir=/usr/lib64 
}
build(){
   ninja -C $BUILDDIR
}

package(){
    DESTDIR=$DESTDIR ninja -C $BUILDDIR install
}
