#!/usr/bin/env bash
name="slang"
version="2.3.3"
description="Multi-platform library designed to allow a developer to create robust software"
source="https://www.jedsoft.org/releases/slang/slang-$version.tar.bz2"
depends="zlib"
builddepend=""
group="sys.libs"


setup(){
	cd $SOURCEDIR
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

