#!/usr/bin/env bash
name="sratom"
version="0.6.14"
url="https://drobilla.net/software/sratom.html"
description="Library for serialising LV2 atoms to/from RDF, particularly the Turtle syntax"

source="https://download.drobilla.net/sratom-$version.tar.xz"
depends="lv2"
group="dev.libs"

setup(){
cd $SOURCEDIR
    meson setup $BUILDDIR --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
   ninja -C $BUILDDIR
}

package(){
   DESTDIR=$DESTDIR ninja -C $BUILDDIR install
}
