#!/usr/bin/env bash
name="newt"
version="0.52.23"
description="Redhat's Newt windowing toolkit development files"
source="https://releases.pagure.org/newt/newt-$version.tar.gz"
depends="slang,popt"
builddepend="libndp"
group="dev.libs"


setup(){
	cd $SOURCEDIR
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

