#!/usr/bin/env bash
name="lv2"
version="1.18.10"
url="https://lv2plug.in/"
description="A simple but extensible successor of LADSPA"

source="https://gitlab.com/lv2/lv2/-/archive/v$version/lv2-v$version.tar.gz"
depends=""
group="media.libs"

setup(){
cd $SOURCEDIR
    meson setup $BUILDDIR --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
   ninja -C $BUILDDIR
}

package(){
   DESTDIR=$DESTDIR ninja -C $BUILDDIR install
}
