#!/bin/bash
name="gnome-keyring"
version="46.1"
description="GNOME keyring. Stores passwords and encryption keys"
source="https://download.gnome.org/sources/gnome-keyring/${version%.*}/gnome-keyring-$version.tar.xz"
depends="dconf,gcr,glib2,glibc,libgcrypt,pam"
builddepend="docbook-xsl,p11-kit.python"
group="dev.libs"


setup(){
	cd $SOURCEDIR
    ./configure --prefix=/usr \
        --libdir=/usr/lib64 \
        --with-pam-dir=/usr/lib64/security \
		--disable-static \
		--disable-doc \
		--disable-schemas-compile

}
build(){
    make
}
package(){
	export GCONF_DISABLE_MAKEFILE_SCHEMA_INSTALL=1
    make DESTDIR=$DESTDIR install
}
