#!/usr/bin/env bash
name="libnftnl"
version="1.2.6"
description="Netfilter library providing interface to the nf_tables subsystem"
source="https://netfilter.org/projects/libnftnl/files/libnftnl-${version}.tar.xz"
depends="libmnl"
group="net.libs"


setup () {
	cd $SOURCEDIR
    ./configure --prefix=/usr \
		--libdir=/usr/lib64/ \
		--sysconfdir=/etc \
		--mandir=/usr/share/man \
		--localstatedir=/var
}

build () {
    make
}

package () {
    make DESTDIR="$DESTDIR" install
}

