#!/usr/bin/env bash
name='gutenprint'
version='5.3.4'
description='Top quality printer drivers for POSIX systems'
source="https://downloads.sourceforge.net/gimp-print/gutenprint-${version}.tar.xz"
depends=""
builddepend="cups,doxygen"
group="net.print"

setup () {
	cd $SOURCEDIR
    ./configure --prefix=/usr \
		--libdir=/usr/lib64/ \
		--sysconfdir=/etc \
		--mandir=/usr/share/man \
		--infodir=/usr/share/info \
		--localstatedir=/var \
		--disable-nls \
		--enable-cups-ppds \
		--enable-simplified-cups-ppds	
}

build () {
    make
}

package () {
    make DESTDIR="$DESTDIR" install
    
    mkdir -p $DESTDIR/usr/lib64
	mv $DESTDIR/usr/lib/* $DESTDIR/usr/lib64/
	rm -rf $DESTDIR/usr/lib
}

