#!/usr/bin/env bash
name="gcr"
version="3.41.1"
description="Libraries for cryptographic UIs and accessing PKCS#11 modules"
source="https://download.gnome.org/sources/gcr/3.41/gcr-$version.tar.xz"
depends="gnupg,openssh,p11-kit,libsecret,gtk3"
builddepend=""
group="app.crypt"


setup(){
	cd $SOURCEDIR
    meson setup $BUILDDIR --prefix=/usr \
		--libdir=/usr/lib64/ \
		-Db_lto=true \
		-Dgtk_doc=false \
		-Dsystemd=disabled
}

build(){
    ninja -C $BUILDDIR
}

package(){
    DESTDIR=$DESTDIR ninja -C $BUILDDIR  install
}

