#!/usr/bin/env bash
name="dotconf"
version="1.3"
description="A C library for parsing configuration files"
source="https://github.com/williamh/dotconf/archive/refs/tags/v${version}.tar.gz"
depends=""
builddepend=""
group="dev.libs"


setup () {
	cd $SOURCEDIR
	autoreconf -fvi
    ./configure --prefix=/usr \
		--libdir=/usr/lib64/ 
}

build () {
    make
}

package () {
    make DESTDIR="${DESTDIR}" install $jobs
}

