#!/usr/bin/env bash
name="gsound"
version="1.0.3"
url="https://wiki.gnome.org/Projects/GSound"
description="Small library for playing system sounds"

source="https://download.gnome.org/sources/gsound/${version%.*}/gsound-${version}.tar.xz"
depends="libcanberr"

group="media.libs"

setup(){
cd $SOURCEDIR
    meson setup $BUILDDIR \
		-Dgtk_doc=false \
		-Dintrospection=true \
		-Denable_vala=true \
		--buildtype=release \
		--prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C $BUILDDIR $jobs
}

package(){
   DESTDIR=$DESTDIR ninja -C $BUILDDIR install $jobs
}

