#!/usr/bin/env bash
name="boost"
version="1.83.0"
_vrs="1_83_0"
description="Free peer-reviewed portable C++ source libraries (development headers)"
source="https://boostorg.jfrog.io/artifactory/main/release/${version}/source/boost_${_vrs}.tar.bz2"
depends="which"
builddepend="which"
group="dev.libs"



setup (){
	cd $SOURCEDIR
	sed -i "/#include.*phoenix.*tuple.hpp.*/d" boost/phoenix/stl.hpp
}

build () {
	./bootstrap.sh --prefix=/usr --with-python=python3
	./b2 stage -j4 threading=multi link=shared
}

package () {
	./b2 --includedir="$DESTDIR"/usr/include \
		--libdir="$DESTDIR"/usr/lib \
		install
}
