#!/usr/bin/env bash
name="iptables"
version="1.8.10"
description="Linux kernel packet control tool (using legacy interface)"
source="https://www.netfilter.org/projects/iptables/files/iptables-${version}.tar.xz"
#source="https://gitlab.com/anadolulinux/anadolulinux/-/raw/master/iptables-1.8.10.tar.xz?ref_type=heads&inline=false"
depends="libnftnl,libmnl"
builddepend="bison,flex"
group="net.firewall"


setup () {
	cp -prvf $PACKAGEDIR/files/ /tmp/bps/build/
	cd $SOURCEDIR
	patch -Np1 -i ../files/use-sh-iptables-apply.patch
	
    ./configure --prefix=/usr \
		--libdir=/usr/lib64/ \
		--mandir=/usr/share/man \
		--sbindir=/sbin \
		--sysconfdir=/etc \
		--without-kernel \
		--enable-devel \
		--enable-libipq \
		--enable-shared

}

build () {
    make
}

package () {
	mkdir -p $DESTDIR/etc/init.d/
	make install DESTDIR="$DESTDIR"

	rm -f $DESTDIR/usr/bin/iptables-xml
	ln -s ../../sbin/xtables-legacy-multi $DESTDIR/usr/bin/iptables-xml

	install -Dm644 include/iptables.h include/ip6tables.h \
		-t "$DESTDIR"/usr/include/
	install -Dm644 include/libiptc/*.h -t "$DESTDIR"/usr/include/libiptc/

	install -D -m755 ../files/iptables.initd "$DESTDIR"/etc/init.d/iptables
	install -D -m644 ../files/iptables.confd "$DESTDIR"/etc/conf.d/iptables
	install -D -m755 ../files/iptables.initd "$DESTDIR"/etc/init.d/ip6tables
	install -D -m644 ../files/ip6tables.confd "$DESTDIR"/etc/conf.d/ip6tables
	install -D -m755 ../files/ebtables.initd "$DESTDIR"/etc/init.d/ebtables
	install -D -m644 ../files/ebtables.confd "$DESTDIR"/etc/conf.d/ebtables

	ln -sfv xtables-nft-multi "$DESTDIR"/sbin/iptables
	ln -sfv xtables-nft-multi "$DESTDIR"/sbin/iptables-save
	ln -sfv xtables-nft-multi "$DESTDIR"/sbin/iptables-restore
	ln -sfv xtables-nft-multi "$DESTDIR"/sbin/ip6tables
	ln -sfv xtables-nft-multi "$DESTDIR"/sbin/ip6tables-save
	ln -sfv xtables-nft-multi "$DESTDIR"/sbin/ip6tables-restore
}

