#!/usr/bin/env bash
name="wireplumber"
version="0.4.14"
url="https://gitlab.freedesktop.org/pipewire/"
description="Session / policy manager implementation for PipeWire"
source="https://gitlab.freedesktop.org/pipewire/wireplumber/-/archive/0.4.14/wireplumber-0.4.14.tar.gz"
depends="pipewire"
group="media.video"

setup(){
	cd $SOURCEDIR
    meson setup $BUILDDIR --prefix=/usr \
    --libdir=/usr/lib64 \
		-Ddoc=disabled \
		-Dsystemd=disabled \
		-Dtests=false \
		--buildtype=release
}

build(){
   ninja -C $BUILDDIR
}

package(){
   DESTDIR=$DESTDIR ninja -C $BUILDDIR install
}
