#!/usr/bin/env bash
name="ftjam"
version="2.5.2"
description="FT Jam - an enhanced version of the Jam build tool"
source="https://master.dl.sourceforge.net/project/freetype/ftjam/$version/ftjam-$version.zip"
depends=""
builddepend=""
group="dev.util"


setup(){
	cd $SOURCEDIR
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

