#!/usr/bin/env bash
name="font-base"
version="1.0.0"
description="X.Org font aliases "
source=""
depends="cantarell-fonts,dejavu,encodings,font-adobe-utopia-type1,font-alias,font-util"
group="media.fonts"

setup(){
	echo ""
}

build(){
   echo ""
}

package(){
mkdir -p $DESTDIR/tmp
touch $DESTDIR/tmp/font-base
 
}

