#!/usr/bin/env bash
name="libbytesize"
version="2.8"
description="A tiny library providing a C "class" for working with arbitrary big sizes in bytes"
source="https://github.com/storaged-project/libbytesize/archive/refs/tags/$version.tar.gz"
depends=""
builddepend=""
group="sys.libs"


setup(){
	cd $SOURCEDIR
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install DESTDIR=$DESTDIR
}

