#!/usr/bin/env bash
name="librsvg"
version="2.58.0"
description="Scalable Vector Graphics (SVG) rendering library "
source="https://download.gnome.org/sources/librsvg/${version%.*}/librsvg-${version}.tar.xz"
depends="libcroco,gobject-introspection,pango,cairo,fontconfig,libX11,libXext,libXrender,libxcb,gdk-pixbuf"
builddepend=""
group="gnome.base"


setup(){
git init -q

	# XXX: Hack to prevent rebuild on install.
	sed -Ei \
		-e 's/^(install-binSCRIPTS:) \$\(bin_SCRIPTS\)/\1/' \
		-e 's/^(install-am:) all-am/\1/' \
		Makefile.in

	export RUSTFLAGS="$RUSTFLAGS -C debuginfo=1"

	cp $PACKAGEDIR/Cargo-update.patch /tmp/bps/build
	cd $SOURCEDIR
	patch -Np1 -i ../Cargo-update.patch

	NOCONFIGURE=1 ./autogen.sh
    #autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
		--libexecdir=/usr/lib64/$name \
		--disable-static \
	    --enable-gtk-doc \
	    --enable-vala

}

build(){
    make
}

package(){
    make install DESTDIR="$DESTDIR"
}

