#!/usr/bin/env bash
name="fuse"
version="3.14.1"
url="https://github.com/libfuse/libfuse"
description="Filesystem in Userspace"
source="https://github.com/libfuse/libfuse/archive/refs/tags/fuse-${version}.tar.gz"
depends="eudev"
group="sys.fs"


setup(){ 
cd $SOURCEDIR
cp -prfv $PACKAGEDIR/fuse.initd  ../$SOURCEDIR/fuse.initd 

    meson setup $BUILDDIR --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Ddefault_library=both \
        -Duseroot=false \
        -Ddisable-mtab=true
}

build(){
    ninja -C $BUILDDIR  $jobs
}

package(){
   DESTDIR=$DESTDIR ninja -C $BUILDDIR  install $jobs
    ln -s fusermount3 $DESTDIR/usr/bin/fusermount
    rm -rf $DESTDIR/dev $DESTDIR/etc/init.d
    mkdir -p $DESTDIR/etc/init.d
    install ../fuse.initd $DESTDIR/etc/init.d/fuse
}
